name: CI

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          
      - name: Install dependencies
        run: yarn
        
      - name: Build
        run: yarn build
        
      - uses: nogsantos/scp-deploy@master
        with:
          src: ./dist/*
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          user: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}          
          remote: ${{ secrets.SSH_DIR }}

